name: readme

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v5

      - name: Install MQ Client
        uses: ./
        with:
          mq-client-version: 9.4.0.0

      - run: dspmqver
